name: mystudy-env
channels:
  - pytorch
  - nvidia
dependencies:
  - h5py
  - tqdm
  - pandas
  - matplotlib
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - scikit-learn=1.7.2
  - hydra-core=1.3.2
  - omegaconf=2.3.0
  - wandb