defaults:
  - mlm_schema

_target_: pretrain.models.MLMModel
name: mlm
wandb_tags: ["mlm"]
lr: 0.0002
weight_decay: 0.01
sptoken_prob: 0.15
mask_prob: 0.8
ernie_rna_alpha: 0.8

arch:
  embed_dim: ${model_size.embed_dim}
  ffn_dim: ${model_size.ffn_dim}
  n_layers: ${model_size.n_layers}
  n_heads: ${model_size.n_heads}
  attention_dropout: ${model_size.attention_dropout}
  rope_max_length: ${dataset.max_length}