hydra:
  job:
    chdir: False  # これをFalseにすると、カレントディレクトリが移動しない
  run:
    dir: ./${path.output_dir}/hydra_configs/${path.timestamp}/train_config # ログの保存場所は確保

defaults:
  - base_config_schema
  - model: knotfold
  - optimizer: adamw
  - _self_

common:
  seed: 42
  batch_size: 2
  max_epochs: 20
  eval_per_epoch: 2 # 1epochあたりの評価回数
  eval_steps: 30
  use_gpu: true
  validation: true
  iterations: 1

pretrain:
  framework: null
  timestamp: null
  checkpoint: ["final"]

path:
  data_dir: ./data/SS_data/
  embedding_dir: ./data/embeddings/
  pretrain_model_dir: ./results/pretrain_results/
  # output_dir: ./results/SS_results/${experiment.name}/${pretrain.framework}/${pretrain.timestamp}/${model.name}/${path.timestamp}/
  output_dir: ./results/SS_results/${experiment.name}/
  timestamp: ${now:%Y%m%dT%H%M%S}

dataset:
  max_length: 512
  sequence_file: ArchiveII.csv
  embedding_file: null
  train_file: train.csv
  validation_file: test.csv
  test_file: test.csv

experiment:
  name: "???"
  additional_experiment_info: null
  use_teacher: false
  use_attention: true
